Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -5,6 +5,7 @@ node {
     echo 'i am in test stage , properties is outside'   
   }
   stage('I am  step 2'){
+  
   echo  'I am in next step2' 
   }
   stage('I am next step 3'){
@@ -17,6 +18,8 @@ node {
 node {
   
   stage('node2 ProPInMiddle'){
+    sh 'exit 1'
+    slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
     echo 'i am in node 2 stage'   
   }
 }
